swagger: '2.0'
info:
  description: Student API Document
  version: 1.0.0
  title: API document Test
  contact:
    email: api@hcmute.edu.vn
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:9000'
basePath: /api
tags:
  - name: student API
    description: External API for testing
    externalDocs:
      description: Find out more
      url: 'http://fit.hcmute.edu.vn/student'
  - name: group
    description: IT K15 HCMUTE
  - name: member
    description: Operations about member
    externalDocs:
      description: Find out more about us
      url: 'http://fit.hcmute.edu.vn/'
schemes:
  - http
paths:
  /student:
    post:
      tags:
        - student
      summary: Add a new student
      description: Add a new student with name and score
      operationId: insert
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: student
          description: Student object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/StudentRequest'
      responses:
        '200':
          description: Insert successfuly
          schema:
            $ref: '#/definitions/ApiResponse'
        '405':
          description: Invalid input
        '500':
          description: System error
    put:
      tags:
        - student
      summary: Update an existing student
      description: ''
      operationId: updateStudent
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: studentRequest
          description: Student object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Student'
      responses:
        '200':
          description: Update successfuly
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Pet not found
        '405':
          description: Invalid input
        '500':
          description: System error
    get:
      tags:
        - student
      summary: Find all student
      description: Returns all students
      operationId: findAllStudent
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Student not found
  '/student/{id}':
    get:
      tags:
        - student
      summary: Find student by ID
      description: Returns a single student
      operationId: getStudentById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of student to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid ID supplied
        '404':
          description: Student not found
    delete:
      tags:
        - student
      summary: Deletes a student
      description: Remove a student
      operationId: deleteStudent
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Student id to delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Delete successfuly
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid ID supplied
        '404':
          description: Student not found
definitions:
  Student:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      name:
        type: string
        example: Như Ý
      score:
        type: number
        example: 10
  StudentRequest:
    type: object
    properties:
      name:
        type: string
        example: Chí Trung
      score:
        type: number
        example: 10
  ApiResponse:
    type: object
    properties:
      type:
        type: string
      message:
        type: string
      data:
        type: object
        $ref: '#/definitions/Student'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
